### ISSUE TITLE
[Data Request]: Climate Data - Near surface air temperatore

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#50] opened 2023-08-01 14:05 UTC
### ID

near_surface_air_temperature

### Description

Variable - Near-surface air temperature , as part of the Copernicus Climate Dataset

**Comment by Mohinem** [comment] 2023-08-01 21:37
@capoony some questions, when you wake up.
1. The dataset contains hourly values of temperatures. Should I upload the data in hourly manner (and you calculate the weekly/monthly data) or calculate the monthly average ?

**Comment by capoony** [comment] 2023-08-02 12:01
> 

@Mohinem Thanks a lot for the inititative, highly appreciated!! ::smile:: The best for us would be daily averages rather than weekly, since our fly samples were collected on a specific day.

Thanks a lot!

@sonjastndl @KathiSchleidt FYI

**Comment by KathiSchleidt** [comment] 2023-08-02 13:44
@Mohinem have you managed to understand the underlying CRS for the climate data? See what came out when I overlaid the near surface temperature with OSM in the [Climate Data Temperature Issue](https://github.com/FAIRiCUBE/data-requests/issues/32#issuecomment-1662079447). Should be solved before we start to import.

In addition, we discussed during today's UC3 meeting if it wouldn't be more efficient to utilize the API available for access to Copernicus Climate Change Service, let you focus on the data from the other services. Have you successfully ingested all other datasets? Scanning the [Project](https://github.com/orgs/FAIRiCUBE/projects/1/views/1), there are still quite a few datasets that haven't even been looked at, e.g. Demography, Elevation (DTM/DSM)...

**Comment by Mohinem** [comment] 2023-08-03 14:10
@KathiSchleidt no I don't know the underlying CRS, and it makes sense to wait for the Climate datasets until we clear that out. But for this particular dataset, I have a transformation which 'looks' good (and to actually know that it's good, it should be verified by UC). At least, it overlays on OSM really well, according to this comment of mine-

https://github.com/FAIRiCUBE/data-requests/issues/32#issuecomment-1662669233

@capoony I finished importing the data. I would like you to verify the dataset - as I have realised that my verification isn't as helpful as the one done by UC owners. The coverage ID is called - near_surface_air_temperature. The underlying CRS is WGS84. 

If there is an issue, I can certainly delete the dataset and reimport again, or wait for the CRS issue to solve, and work on it again.

**Comment by KathiSchleidt** [comment] 2023-08-06 12:47
@Mohinem 
I've responded on #32, still see some issues!

I've also now added @capoony to the assignees on this issue

**Comment by capoony** [comment] 2023-08-06 13:34
Dear @KathiSchleidt, Dear @Mohinem, thanks so much for your work on this and for spotting unresolved issues!All the very best and happy Sunday,Martin********************************************************Martin Kapun, PhDBioinformatician Natural History Museum ViennaCentral Research LaboratoriesBurgring 7A-1010 WienIndependent Group LeaderLab of Genome DynamicsDept Cell & Developmental BiologyCenter of Anatomy and Cell Biology Medical University of Vienna,  Schwarzspanierstr. 17, HP 36   A-1090 Vienna https://www.researchgate.net/profile/Martin_Kapun********************************************************Am 06.08.2023 um 14:48 schrieb Kathi Schleidt ***@***.***>:﻿
@Mohinem
I've responded on #32, still see some issues!
I've also now added @capoony to the assignees on this issue

**Comment by pebau** [comment] 2023-08-30 13:54
no, not supported.

**Comment by KathiSchleidt** [comment] 2023-08-30 14:00
Trying to understand. I'd been under the impression that the AnsiDate CRS you utilize works in seconds. I get the problem that we cannot provide a fixed number of seconds for a year, as this is irregular due to leap-years.

However, I was under the impression that the number of seconds in a day can still be calculated as 60*60*24=86400, allowing for a regular interval. Or do we also run into leap-days there?

Conclusion: time in coverages can only be enumerated when intervals are over 1sec - is this correct?

**Comment by pebau** [comment] 2023-08-30 14:08
can we have an example of what is desired?

**Comment by KathiSchleidt** [comment] 2023-09-01 10:25
To my understanding, when using the AnsiDate CRS to define a grid, one can indicate data being provided in regular temporal intervals based on seconds, parallel to indicating data being provided in regular spatial intervals based on the spatial CRS (intervals provided in either degrees or m, depending on CRS).

For data with a temporal interval beyond seconds (hours, days, years), we'd like a similar approach to the spatial CRS or temporal CRS with seconds, being able to indicate a temporal dimension with an interval for the offset, whereby this offset is in hours, days or years (far more common in the data we're dealing with than seconds).

Examples:
- Hourly: Near Surface Temperature
- Yearly: Corine Land Cover, time coverage: 1990 2000 2006 2012 2018

I understand the issues in aggregating seconds to years, as the number of seconds can vary due to leap-years. At the same time, I see a strong requirement for being able to indicate hourly, daily or yearly values (without having to enumerate each individual time instant). Reason I proposed investigating creating a CRS based on hours, days or years for such purposes.

Also - is it true that the Corine Land Cover dataset is incorrect, as there you utilize a RectifiedGrid, indicate the temporal intervals by an offsetVector of 1day?

**Comment by KathiSchleidt** [comment] 2023-09-11 17:33
related to #61 

@pebau Is it correct that all coverages provided on rasdaman will modified to ReferenceableGridByVectors, as just about all datasets have at least 2 points in time for which they provide data?

First feedback from NHM is that the long enumeration of days (we're not even at hours yet) is not really user-friendly

**Comment by KathiSchleidt** [comment] 2023-09-11 19:02
@pebau having now taken a closer look at the [AnsiDate CRS](https://www.opengis.net/def/crs/OGC/0/AnsiDate), I've realized that your statement that this CRS was based on seconds is wrong, AnsiDate is defined as:
`Concrete temporal CRS of days elapsed from 1-Jan-1601 (00h00 UTC).`

Thus, for daily values, one could actually use the encoding currently incorrectly used for years (example from corine_land_cover):

`<gml:Envelope axisLabels="ansi Y X" uomLabels="d metre metre" ...`

Could you please explain why the one dataset for which we could correctly utilize AnsiDate uses ReferenceableGridByVectors and an enumeration of all days, while the tri-yearly datasets indicate daily?

**Comment by sonjastndl** [comment] 2023-09-13 12:19
Is there any advice on how to deal with these GeoExtent specifications? Additionaly, can changes/updates on data maybe be notified?
![264338097-bf0659bc-a321-4aea-a4c4-cbaac1a386b2](https://github.com/FAIRiCUBE/data-requests/assets/56771750/e7846404-5aa3-42f7-9e79-326f77809140)

**Comment by pebau** [comment] 2023-09-13 12:33
happy to explain, but first: what do you have in mind with "deal with" ? If it is subsetting, you can use such coordinates in a WCPS query, and the geo extent tells you the limits (likewise time). In this case, geo is spanning the whole planet, so no real constraint unless you want to wrap around.

**Comment by KathiSchleidt** [comment] 2023-09-14 11:00
@pebau I think what is irritating in the extent of near_surface_air_temperature is the fact that it doesn't cleanly wrap around from -180 to 180 - I'm assuming this has to do with the fact that this dataset sees pixel-as-area (there's a value for the point 0,0, with the corresponding grid cell spanning from -0.25-0.25 on both axes) - can you confirm this?

In addition, could you please provide an answer to my question above, why near_surface_air_temperature indicates daily values via AnsiDate, then utilizes ReferenceableGridByVectors to enumerate all days?

**Comment by sonjastndl** [comment] 2023-09-14 12:07
@pebau I know we talked about this shortly in our last conversation, and for example when transforming to another EPSG there was a quick mentioning of some other gdal-function than gdal osr.CoordinateTransform. Sadly I cannot remember if there was any specific function that was suggested, that recognizes input CRS automatically or this was a sugestion to look for one.

Also, if there is no transformation of EPSG necessary, and e.g. there would be a sample point of Y = -179,76 (theoretically), how should data like this be handled automatically in terms of conversion to then ...180,24..?
Since this seems to be an accepted practice, I was wondering if there already some state of the art request-handling-strategies floating around...

**Comment by KathiSchleidt** [comment] 2023-09-28 14:55
@pebau I found the [WCS Spec (OGC 09-110r4)](https://portal.ogc.org/files/09-110r4), found the relevant section on Single Dimension Trimming. 

Apart from finding an error in the standard, I've documented the expected behavior based on Requirement 38 from this standard. 

Details in the [Coverage Subsetting Issue](https://github.com/FAIRiCUBE/data-requests/blob/main/encoding-examples/Coverage%20Subsetting%20Issue.docx) doc.

When can we expect rasdaman to return data in accordance with WCS?

**Comment by pebau** [comment] 2023-10-02 17:37
> In addition, could you please provide an answer to my question above, why near_surface_air_temperature indicates daily values via AnsiDate, then utilizes ReferenceableGridByVectors to enumerate all days?

on this one specifically (for the other one I have to ask back): cannot see a problem here - users = query writers see no difference.

**Comment by KathiSchleidt** [comment] 2023-10-02 18:47
@pebau no difference to the user requesting data from the WCS, but big different to the user parsing the resulting coverage response :(

**Comment by pebau** [comment] 2023-10-03 16:51
hm...can I see the parsing that needs to be done (or is done already), to understand better?

**Comment by KathiSchleidt** [comment] 2023-10-04 09:46
@pebau are you trying to explain that all the XML apart from the rangeSet is irrelevant to users? DescribeCoverage can be removed?

Based on the issues encountered in getting a correct response for WCS subsetting, we've become increasingly dependent on this additional descriptive information. Would be nice if the structure were consistent

**Comment by KathiSchleidt** [comment] 2023-11-27 14:54
@Mohinem this dataset is a beautiful example of the power of metadata! When looking at the temperature values, I was a bit confused:
```
<cis11:V>281.9675</cis11:V>
<cis11:V>281.4334</cis11:V>
<cis11:V>282.0142</cis11:V>
```
I had to backtrack via the data request issue to the original source to see that this temperature data is being provided in Kelvin. Once more showing that without such metadata, the data is just numbers, no longer data

**Comment by pebau** [comment] 2024-01-11 10:57
while I appreciate how a lot of information has been collected it is disparate and we cannot ingest on this basis. Closing this, please feel free to 
insufficient information for ingestion, so closing. Feel free to file a [complete request](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data).

**Closed** 2024-01-11 10:58 UTC
Labels: data-request, Target rasdaman
